import { Assay001wb } from "src/entity/Assay001wb";
import { Assaytype001mb } from "src/entity/Assaytype001mb";
import { Category001mb } from "src/entity/Category001mb";
import { Categoryfunction001mb } from "src/entity/Categoryfunction001mb";
import { Ligand001wb } from "src/entity/Ligand001wb";
import { Originalprefix001mb } from "src/entity/Originalprefix001mb";
import { Routeofadministration001mb } from "src/entity/Routeofadministration001mb";
import { Toxicity001mb } from "src/entity/Toxicity001mb";
import { Type001mb } from "src/entity/Type001mb";
import { Unitlowendvalue001mb } from "src/entity/Unitlowendvalue001mb";
import { Unitsinglevalue001mb } from "src/entity/Unitsinglevalue001mb";

export class AssayDTO {
    assayId: number;
    ordinal: string;
    collectionId: string;
    ligandSlno: number;
    assayTypeSlno: number;
    toxiCitySlno: number;
    routeSlno: number;
    ligandSvalue: string;
    unitSlno: number;
    ligandHvalue: string;
    ligandLvalue: string;
    administration: string;
    procedure: string;
    conditionType: string;
    conditionMaterial: string;
    conditionMaterialid: string;
    singleCondition: string;
    singleUnit: string;
    highCondition: string;
    lowCondition: string;
    highLowUnit: string;
    unitedSlno: number;
    status: string;
    dataLocator: string;
    dataLocator1: string | null;
    dataLocator2: string | null;
    dataLocator3: string | null;
    categorySlno: number;
    functionSlno: number;
    parameter: string;
    parameterDetail: string;
    singleValue: string;
    unit: string;
    originalPrefixSlno: number;
    highEndValue: string;
    lowEndValue: string;
    units: string;
    nonNumeric: string;
    remark: string;
    typeSlno: number;
    cell: string;
    cellDetail: string;
    organ: string;
    organDetail: string;
    species: string;
    speciesDetail: string;
    gender: string | null;
    ageGroup: string;
    target: string;
    targetVersion: string;
    targetStatus: string;
    collectionId1: string;
    original: string;
    acronym: string;
    organism: string;
    variant: string;
    insertUser: string;
    insertDatetime: Date;
    updatedUser: string | null;
    updatedDatetime: Date | null;

    ligandSlno2: Ligand001wb[];
    assayTypeSlno2: Assaytype001mb;
    toxiCitySlno2: Toxicity001mb;
    routeSlno2: Routeofadministration001mb;
    unitSlno2: Unitsinglevalue001mb;
    unitedSlno2: Unitlowendvalue001mb;

    categorySlno2: Category001mb;
    functionSlno2: Categoryfunction001mb;
    originalPrefixSlno2: Originalprefix001mb;
    typeSlno2: Type001mb;
    
    setProperties(assay001wb: Assay001wb) {
        // this.assayId = assay001wb.assayId;
        // this.ordinal = assay001wb.ordinal;
        // this.collectionId = assay001wb.collectionId;
        // this.ligandSlno = assay001wb.ligandSlno;
        // this.assayTypeSlno = assay001wb.assayTypeSlno;
        // this.toxiCitySlno = assay001wb.toxiCitySlno;
        // this.routeSlno = assay001wb.routeSlno;
        // this.ligandSvalue = assay001wb.ligandSvalue;
        // this.unitSlno = assay001wb.unitSlno;
        // this.ligandHvalue = assay001wb.ligandHvalue;
        // this.ligandLvalue = assay001wb.ligandLvalue;
        // this.administration = assay001wb.administration;
        // this.procedure = assay001wb.procedure;
        // this.target = assay001wb.target;
        // this.conditionType = assay001wb.conditionType;
        // this.conditionMaterial = assay001wb.conditionMaterial;
        // this.conditionMaterialid = assay001wb.conditionMaterialid;
        // this.singleCondition = assay001wb.singleCondition;
        // this.singleUnit = assay001wb.singleUnit;
        // this.highCondition = assay001wb.highCondition;
        // this.lowCondition = assay001wb.lowCondition;
        // this.highLowUnit = assay001wb.highLowUnit;
        // this.unitedSlno = assay001wb.unitedSlno;
        // this.status = assay001wb.status;
        // this.insertUser = assay001wb.insertUser;
        // this.insertDatetime = assay001wb.insertDatetime;
        // this.updatedUser = assay001wb.updatedUser;
        // this.updatedDatetime = assay001wb.updatedDatetime;

        this.assayId = assay001wb.assayId;
        this.ordinal = assay001wb.ordinal;
        this.collectionId = assay001wb.collectionId;
        this.ligandSlno = assay001wb.ligandSlno;
        this.assayTypeSlno = assay001wb.assayTypeSlno;
        this.toxiCitySlno = assay001wb.toxiCitySlno;
        this.routeSlno = assay001wb.routeSlno;
        this.ligandSvalue = assay001wb.ligandSvalue;
        this.unitSlno = assay001wb.unitSlno;
        this.ligandHvalue = assay001wb.ligandHvalue;
        this.ligandLvalue = assay001wb.ligandLvalue;
        this.administration = assay001wb.administration;
        this.procedure = assay001wb.procedure;
        this.target = assay001wb.target;
        this.conditionType = assay001wb.conditionType;
        this.conditionMaterial = assay001wb.conditionMaterial;
        this.conditionMaterialid = assay001wb.conditionMaterialid;
        this.singleCondition = assay001wb.singleCondition;
        this.singleUnit = assay001wb.singleUnit;
        this.highCondition = assay001wb.highCondition;
        this.lowCondition = assay001wb.lowCondition;
        this.highLowUnit = assay001wb.highLowUnit;
        this.unitedSlno = assay001wb.unitedSlno;
        this.status = assay001wb.status;
        this.dataLocator = assay001wb.dataLocator;
        this.dataLocator1 = assay001wb.dataLocator1;
        this.dataLocator2 = assay001wb.dataLocator2;
        this.dataLocator3 = assay001wb.dataLocator3;
        this.categorySlno = assay001wb.categorySlno;
        this.functionSlno = assay001wb.functionSlno;
        this.parameter = assay001wb.parameter;
        this.parameterDetail = assay001wb.parameterDetail;
        this.singleValue = assay001wb.singleValue;
        this.unit = assay001wb.unit;
        this.originalPrefixSlno = assay001wb.originalPrefixSlno;
        this.highEndValue = assay001wb.highEndValue;
        this.lowEndValue = assay001wb.lowEndValue;
        this.units = assay001wb.units;
        this.nonNumeric = assay001wb.nonNumeric;
        this.remark = assay001wb.remark;
        this.typeSlno = assay001wb.typeSlno;
        this.cell = assay001wb.cell;
        this.cellDetail = assay001wb.cellDetail;
        this.organ = assay001wb.organ;
        this.organDetail = assay001wb.organDetail;
        this.species = assay001wb.species;
        this.speciesDetail = assay001wb.speciesDetail;
        this.gender = assay001wb.gender;
        this.ageGroup = assay001wb.ageGroup;
       
        this.target = assay001wb.target;
        this.targetVersion = assay001wb.targetVersion;
        this.targetStatus = assay001wb.targetStatus;
        this.collectionId1 = assay001wb.collectionId1;
        this.original = assay001wb.original;
        this.acronym = assay001wb.acronym;
        this.organism = assay001wb.organism;
        this.variant = assay001wb.variant;
       
        this.insertUser = assay001wb.insertUser;
        this.insertDatetime = assay001wb.insertDatetime;
        this.updatedUser = assay001wb.updatedUser;
        this.updatedDatetime = assay001wb.updatedDatetime;
    }
}